web-ui/navbar: reportAppError instead of displayInitError
Because displayInitError causes an error itself:

  Error: Element is missing: #init-error-message

...and the initial error is lost.