Replace Node structuredClone with @ungap/structured-clone
Because structuredClone in Node 22 cannot clone URL objects:

    ~/src/rss-email-subscription ɀ  node -p 'structuredClone(new URL("http://g.com"))'
node:internal/worker/js_transferable:126
  const serializedData = nativeStructuredClone(value, idlOptions);
                         ^

DataCloneError: Cannot clone object of unsupported type.
    at new DOMException (node:internal/per_context/domexception:53:5)
    at structuredClone (node:internal/worker/js_transferable:126:26)
    at [eval]:1:1
    at runScriptInThisContext (node:internal/vm:209:10)
    at node:internal/process/execution:118:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:101:62)
    at evalScript (node:internal/process/execution:136:3)
    at node:internal/main/eval_string:55:3

Node.js v22.13.1